stages:
  - build

default:
  tags: [ docker ]

variables:
  # to run OpenMPI in docker
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  OMPI_MCA_btl_vader_single_copy_mechanism: none

before_script:
  - echo 'localhost slots=8' > /etc/openmpi/openmpi-default-hostfile
  - apt-get install -yq intel-mkl-core-c-2020.4-304
  - ln -s /opt/intel/compilers_and_libraries_2020.4.304/linux/mkl/ /opt/intel/

build:
  stage: build
  timeout: 3h
  image: valeevgroup/${IMAGE}
  variables:
    CXX: ${CXX}
    TA_PYTHON : "TA_PYTHON=OFF"
    BLAS : ""
    ENABLE_SCALAPACK : "ENABLE_SCALAPACK=OFF"
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/gitlab-ci.cmake
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
        -D${TA_PYTHON}
        -D${ENABLE_SCALAPACK}
        ${BLAS}
    - make tiledarray
    - make examples
    - make ta_test
    - make check
  parallel:
    matrix:
      - CXX: [ g++ ]
        IMAGE : [ "ubuntu:20.04" ]
        BUILD_TYPE : [ "Release", "Debug" ]
        BLAS : [ "-DBLA_VENDOR=Intel10_64lp_seq", "-DBLA_VENDOR=Intel10_64lp", "" ]
        ENABLE_SCALAPACK : [ "ENABLE_SCALAPACK=ON", "ENABLE_SCALAPACK=OFF" ]
      - CXX: [ g++ ]
        IMAGE : [ "ubuntu:20.04" ]
        BUILD_TYPE : [ "Release", "Debug" ]
        TA_PYTHON : [ "TA_PYTHON=ON" ]
      - CXX: [ clang++-9 ]
        IMAGE : [ "ubuntu:20.04" ]
        BUILD_TYPE : [ "Release", "Debug" ]
        BLAS : [ "-DBLA_VENDOR=Intel10_64lp_seq", "-DBLA_VENDOR=Intel10_64lp", "" ]
