language: cpp
cache: ccache
os: linux
compiler:
  - gcc
  - clang
env:
  - GCC_VERSION=4.7
  - GCC_VERSION=4.8
  - GCC_VERSION=4.9
  - GCC_VERSION=5
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=4.7
    - compiler: clang
      env: GCC_VERSION=4.8
    - compiler: clang
      env: GCC_VERSION=4.9
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-precise-3.9
    packages:
      - g++-4.7
      - g++-4.8
      - g++-4.9
      - g++-5
# llvm.org apt repo is down
      - clang-3.9
      - libeigen3-dev
      - libboost1.55-dev
      - libblas-dev
      - liblapack-dev
      #- mpich2 # disallowed - build from source
      - libtbb-dev
      - cmake
      - cmake-data
#notifications:
#  email:
#    recipients:
#      - @github.com
#    on_success: change
#    on_failure: always
before_install: ./bin/dep-$TRAVIS_OS_NAME.sh
script: ./bin/build-$TRAVIS_OS_NAME.sh
after_failure:
  - cat ./_build/external/build/madness/CMakeFiles/CMakeOutput.log
  - cat ./_build/external/build/madness/CMakeFiles/CMakeError.log
  - cat ./_build/CMakeFiles/CMakeOutput.log
  - cat ./_build/CMakeFiles/CMakeError.log