language: cpp
cache: ccache
cache:
  directories:
  - /home/travis/_install
os: linux

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test
      - boost-latest
      - kubuntu-backports
    sources: &clang_sources
      - llvm-toolchain-trusty-5.0
    packages: &base_packages
    - libeigen3-dev
    - libboost1.55-all-dev
    - libblas-dev
    - liblapack-dev
    - libtbb-dev
    - cmake
    - cmake-data

env:
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: GCC_VERSION=4.9 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-4.9
           - gfortran-4.9
    - compiler: gcc
      env: GCC_VERSION=4.9 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-4.9
           - gfortran-4.9
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-5
           - gfortran-5
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-5
           - gfortran-5
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-6
           - gfortran-6
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-6
           - gfortran-6
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-7
           - gfortran-7
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
          packages:
           - *base_packages
           - g++-7
           - gfortran-7
    - compiler: clang
      env: GCC_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
           - *base_sources
           - *clang_sources
          packages:
           - *base_packages
           - g++-7
           - gfortran-7
           - clang-5.0
    - compiler: clang
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          sources:
           - *base_sources
           - *clang_sources
          packages:
           - *base_packages
           - g++-7
           - gfortran-7
           - clang-5.0

#notifications:
#  email:
#    recipients:
#      - @github.com
#    on_success: change
#    on_failure: always
before_install:
  - env
  - mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}
# use timeout to stop long-running (i.e. cache-rebuilding) jobs right before they get killed by Travis-CI
# in case of timeout report success to Travis to force cache upload
script:
  - travis_wait 50 timeout 2200 ./bin/build-$TRAVIS_OS_NAME.sh;  RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 124 ]; then true; else false; fi;
after_failure:
  - cat ${BUILD_PREFIX}/TA/external/build/madness/CMakeFiles/CMakeError.log
  - cat ${BUILD_PREFIX}/TA/external/build/madness/CMakeFiles/CMakeOutput.log
  - cat ${BUILD_PREFIX}/TA/CMakeFiles/CMakeError.log
  - cat ${BUILD_PREFIX}/TA/CMakeFiles/CMakeOutput.log
